### PR TITLE
feat(core): Allows shell to use ansible variables

### PR DESCRIPTION
**Pull request by voryzen**
Creates a ansible_bash.vars file when setting up VivumLab.

Shell commands/ tasks can use these variables.

### CODE REVIEW

**Comment by voryzen** [comment]
I've got some more code that I would like to add, but it requires this to be merged.

Let me know if you like it. The extra code that i refer to above, I find very useful

**Review by denis-ev — CHANGES_REQUESTED** [review]
@voryzen I really like this, but there is a conflict atm

**Review by voryzen — COMMENTED** [review]
added new lines at end of file

**Comment by voryzen** [comment]
should have tied up all the loose ends..

might be better to merge this PR, before the other

**Review by denis-ev — APPROVED** [review]

**Pull request merged**
